name: gator
description: Generate MaterialColor shades and tints from primary colors hex values for easy setup.
version: 1.5.0
repository: https://github.com/Luckey-Elijah/gator

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.0
  built_collection: ^5.1.1
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  equatable: ^2.0.3
  mason_logger: ^0.3.1
  meta: ^1.7.0
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  mocktail: ^1.0.1
  path: ^1.8.1
  test: ^1.16.0
  very_good_analysis: ^6.0.0

executables:
  gator:
