name: gator
description: Generate shades and tints from primary colors hex values for easy setup.
version: 1.2.1
repository: https://github.com/Luckey-Elijah/gator

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0
  built_collection: ^5.1.1
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  equatable: ^2.0.3
  mason_logger: ^0.1.0-dev.4
  meta: ^1.7.0
  path: ^1.8.1
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0

executables:
  gator:

